$htmlPath = "d:\CCTV\Projects\FinixSoftware\finix_frontend\src\app\features\tiempo\gestion-tiempo\gestion-tiempo.component.html"
$html = Get-Content $htmlPath -Raw
$html = $html -replace '<h2><i class="fa-solid fa-clock-rotate-left mr-2"></i>Historial de Tiempos Cobrados</h2>', "<h2><i class=`"fa-solid fa-clock-rotate-left mr-2`"></i>Historial de Tiempos Cobrados</h2>`n        <div class=`"flex items-center space-x-4 mb-4`">`n            <input type=`"date`" [(ngModel)]=`"fechaFiltro`" (change)=`"cargarHistorial()`" class=`"p-2 rounded border dark:bg-slate-700 dark:text-white dark:border-slate-600`">`n            <input type=`"text`" (keyup)=`"applyFilter(`$event)`" placeholder=`"Buscar...`" class=`"p-2 rounded border dark:bg-slate-700 dark:text-white dark:border-slate-600`">`n        </div>"
$html = $html -replace '\[dataSource\]="sesionesFinalizadas\(\)"', '[dataSource]="dataSourceFinalizadas"'
$html = $html -replace '<ng-container matColumnDef="cobrado">', "<ng-container matColumnDef=`"adicionales`">`n              <th mat-header-cell *matHeaderCellDef> Productos Adicionales </th>`n              <td mat-cell *matCellDef=`"let s`">`n                 <ul class=`"text-xs m-0 pl-4`">`n                    <li *ngFor=`"let prod of s.adicionales`">`n                       {{prod.cantidad}}x {{prod.productoNombre}} (\${{prod.totalVenta | number:'1.0-0'}})`n                    </li>`n                 </ul>`n              </td>`n            </ng-container>`n`n            <ng-container matColumnDef=`"cobrado`">"
$html = $html -replace "displayedColumnsHistorial: string\[\] = \['equipo', 'inicio', 'fin', 'duracion', 'cobrado'\];", "displayedColumnsHistorial: string[] = ['equipo', 'inicio', 'fin', 'duracion', 'adicionales', 'cobrado'];"
$html = $html -replace '@if \(!sesionesFinalizadas\(\)\.length\) \{', '@if (!dataSourceFinalizadas.data.length) {'
$html = $html -replace '</table>[\s\S]*?</div>', "</table>`n        <mat-paginator [pageSizeOptions]=`"[10, 25, 50]`" showFirstLastButtons></mat-paginator>`n      </div>"
Set-Content $htmlPath -Value $html
